[package]
name = "ultimate-tic-tac-toe"
version = "0.1.0"
authors = ["row454 <rowanhope5@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }

[features]
default = []
cli = []